boostcampwm-2021/Android08-Ratatouille

app/src/main/java/com/kdjj/ratatouille/di/RepositoryModule.kt
app/src/main/java/com/kdjj/ratatouille/di/presentation/FakeModule.kt
domain/src/main/java/com/kdjj/domain/usecase/FetchRecipeTypesUseCase.kt

- Hilt에서 List를 그냥 사용하면 Kotlin List의 제너릭 타입 `<out E>` 때문에 에러 발생
- `@JvmSuppressWildcards`를 사용하여 자바 코드가 생성될 때 <? extends> 가 붙지 않도록 함

[develop] Hilt에서 List 사용 시 발생하는 에러 해결

---

app/src/main/java/com/kdjj/ratatouille/di/data/RecipeListModule.kt
data/build.gradle
data/src/main/java/com/kdjj/data/datasource/RecipeListRemoteDataSource.kt
data/src/main/java/com/kdjj/data/repository/RecipeListRepositoryImpl.kt
domain/src/main/java/com/kdjj/domain/repository/RecipeListRepository.kt
domain/src/main/java/com/kdjj/domain/request/FetchRemoteLatestRecipeListRequest.kt
domain/src/main/java/com/kdjj/domain/request/FetchRemotePopularRecipeListRequest.kt
domain/src/main/java/com/kdjj/domain/request/FetchRemotePopularRecipeListRequset.kt
domain/src/main/java/com/kdjj/domain/request/FetchRemoteSearchRecipeListRequest.kt
domain/src/main/java/com/kdjj/domain/usecase/FetchRemoteLatestRecipeListUseCase.kt
domain/src/main/java/com/kdjj/domain/usecase/FetchRemotePopularRecipeListUseCase.kt
domain/src/main/java/com/kdjj/domain/usecase/FetchRemoteSearchRecipeListUseCase.kt
remote/src/main/java/com/kdjj/remote/dao/RecipeListDao.kt
remote/src/main/java/com/kdjj/remote/dao/RecipeListDaoImpl.kt
remote/src/main/java/com/kdjj/remote/datasource/RecipeListRemoteDataSourceImpl.kt

704b3a84281a3f72758eebf8880ca903fb64b1c2
presentation 에서 페이징 처리 할 때 참고해주세요 .
Room 과 달리 query  orderby limit offset  으로 paging 처리가 안 됩니다.( firestore에서 offset을 지원하지 않음 ) 
```kotlin
firestore.collection(RECIPE_COLLECTION_ID)
.orderBy(FIELD_CREATE_TIME, Query.Direction.DESCENDING)
.startAfter(lastVisibleCreateTime)
.limit(PAGING_SIZE)
.get()
.await()
.map { queryDocumentSnapshot ->
entityToDomain(queryDocumentSnapshot.toObject<RecipeEntity>())
}
```
first page 가져올때 lastVisibleCreateTime에 0 넣으면 맨 앞에서 부터 page Size 만큼 가져옵니다! 
lastVisible... 이 String 일땐 empty String 넣어주면 됩니다. 
더 이상 가져올게 없는 경우 emptyList 리턴 합니다. 
2435b046b9d0d71f0593abdb710e8bbfa164452c
discussion 참고해주세요.
https://github.com/boostcampwm-2021/Android08-Ratatouille/discussions/47

[develop] 서버 레시피 리스트 로드 ( domain, data, remote ) 

---

presentation/src/main/java/com/kdjj/presentation/common/Utils.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/BaseListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/OthersRecipeListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/home/HomeActivity.kt
presentation/src/main/java/com/kdjj/presentation/view/home/others/OthersRecipeFragment.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/others/OthersViewModel.kt
presentation/src/main/res/drawable/ic_eye.xml
presentation/src/main/res/layout/fragment_others_recipe.xml
presentation/src/main/res/layout/item_others_recipe.xml
presentation/src/main/res/values/strings.xml

Issue : https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/60
힐끔보기 화면 UI 작업
상단 appbar, 레시피 목록 recyclerview, 목록 필터링 radiobutton
제네릭 base adpater 및 viewholder 작성
BaseListApdater 와 BaseViewHolder를 만들었습니다 4ce0c6062971b2a2dcffec5a371e24c1953f5e99
BaseListAapter는 viewType이 1개일 때 사용하면 될 것 같습니다 cfaeb75

[develop] 힐끔보기 화면 UI 

---

domain/src/main/java/com/kdjj/domain/usecase/SaveRecipeUseCase.kt

SaveRecipeUseCase 레시피 이미지 저장하는 로직 추가 #73
SaveRecipeUseCase 이미지 저장하는 로직 추가
- SaveRecipeUseCase 이미지 저장하는 로직 추가
RecipeImageRepository에서 빈 문자열을 받으면 Exception이 나면서 발생한 문제
imgPath.isNotEmpty()를 이용하여 빈 문자열이 들어올 경우 빈 값을 저장하도록 처리
처리 중 imgPath를 null로 하는건 어떤지 의견이 나옴
추후 토론 예정

[develop] SaveRecipeUseCase 레시피 이미지 저장하는 로직 추가 #73

---

data/src/main/java/com/kdjj/data/common/ResultExtension.kt
data/src/main/java/com/kdjj/data/datasource/RecipeListLocalDataSource.kt
data/src/main/java/com/kdjj/data/repository/RecipeListRepositoryImpl.kt
domain/src/main/java/com/kdjj/domain/model/request/FetchLocalLatestRecipeListRequest.kt
domain/src/main/java/com/kdjj/domain/model/request/FetchLocalTitleRecipeListRequest.kt
domain/src/main/java/com/kdjj/domain/repository/RecipeListRepository.kt
domain/src/main/java/com/kdjj/domain/usecase/FetchLocalLatestRecipeListUseCase.kt
domain/src/main/java/com/kdjj/domain/usecase/FetchLocalTitleRecipeListUseCase.kt
domain/src/main/java/com/kdjj/domain/usecase/SaveLocalRecipeUseCase.kt
local/src/main/java/com/kdjj/local/FileSaveHelper.kt
local/src/main/java/com/kdjj/local/dao/RecipeListDao.kt
local/src/main/java/com/kdjj/local/dataSource/RecipeListLocalDataSourceImpl.kt
local/src/main/java/com/kdjj/local/dataSource/RecipeLocalDataSourceImpl.kt
local/src/main/java/com/kdjj/local/dataSource/RecipeTypeLocalDataSourceImpl.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/BaseListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/OthersRecipeListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/SingleViewTypeListAdapter.kt
remote/src/main/java/com/kdjj/remote/dao/FirebaseStorageServiceImpl.kt
remote/src/main/java/com/kdjj/remote/datasource/RecipeListRemoteDataSourceImpl.kt
remote/src/main/java/com/kdjj/remote/datasource/RecipeRemoteDataSourceImpl.kt
remote/src/main/java/com/kdjj/remote/datasource/RecipeTypeRemoteDataSourceImpl.kt

Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/80
- erroMap 에서 throwable 을 nonNullable 하게 수정
- BaseListAdapter 에서 viewType 넘겨주는 것 제거
BaseListAdapter는 viewType 하나 일때 사용가능하므로, viewType을 하나하나 넘겨줄 필요가 없다
- 최신순 정렬 할때 최신순이 아닌 문제 -> orderby ascending
- erroMap 수정 c4ff0dac45411245ed9175dae173390e472141a6
- BaseListAdapter 수정 bfa126736d05160d2dbb5c7d46928b96c38aec3e
- 로컬 레시피 리스트 가져올 때 orderby ascending beaaf069daff59ae2d9df07908762e891c00074f

[develop] errormap, base list adapter, 로컬 레시피 리스트 정렬 수정

---

data/src/main/java/com/kdjj/data/datasource/RecipeImageLocalDataSource.kt
data/src/main/java/com/kdjj/data/repository/RecipeImageRepositoryImpl.kt
data/src/test/java/com/kdjj/data/recipeimage/RecipeImageRepositoryImplTest.kt
domain/src/main/java/com/kdjj/domain/repository/RecipeImageRepository.kt
domain/src/main/java/com/kdjj/domain/usecase/SaveLocalRecipeUseCase.kt
local/src/main/java/com/kdjj/local/FileSaveHelper.kt
local/src/main/java/com/kdjj/local/dataSource/RecipeImageLocalDataSourceImpl.kt
local/src/test/java/com/kdjj/local/dataSource/RecipeImageLocalDataSourceImplTest.kt

이미지가 저장될때 각도가 돌아가는 현상을 수정함
UseCase에서 Image 저장 처리에되한 성공 여부를 관리하다 Repository 에서 하도록 변경
없음

[develop] RecipeImage, UseCase, Repository, LocalDataSource, FileSaveHelper 수정

---

domain/src/main/java/com/kdjj/domain/di/UseCaseModule.kt
domain/src/main/java/com/kdjj/domain/model/request/GetLocalRecipeFlowRequest.kt
domain/src/main/java/com/kdjj/domain/usecase/FetchRecipeTypeListUseCase.kt
domain/src/main/java/com/kdjj/domain/usecase/GetLocalRecipeFlowUseCase.kt
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/kdjj/presentation/common/Utils.kt
presentation/src/main/java/com/kdjj/presentation/view/bindingadapter/TextViewBindingAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/recipesummary/RecipeSummaryActivity.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt
presentation/src/main/res/layout/activity_recipe_detail.xml
presentation/src/main/res/layout/activity_recipe_summary.xml
presentation/src/main/res/layout/item_my_recipe.xml
presentation/src/main/res/values/dimens.xml
presentation/src/main/res/values/strings.xml
presentation/src/main/res/values/styles.xml

Issue #103 
- 레시피 개요 페이지 생성
- 레시피 개요 페이지 디자인 추가

[develop] 레시피 개요 페이지 디자인 구현

---

presentation/src/main/java/com/kdjj/presentation/model/OthersRecipeModel.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/OthersRecipeListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/home/others/OthersRecipeFragment.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/others/OthersViewModel.kt
presentation/src/main/res/navigation/navigation.xml
presentation/src/main/res/values/strings.xml

Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/112
힐끔 보기 화면에서 레시피 개요 화면 이동

[develop] 힐끔 보기 화면에서 레시피 개요 화면으로 이동 #112

---

data/src/main/java/com/kdjj/data/repository/RecipeRepositoryImpl.kt
domain/src/main/java/com/kdjj/domain/di/UseCaseModule.kt
domain/src/main/java/com/kdjj/domain/repository/RecipeRepository.kt
domain/src/main/java/com/kdjj/domain/usecase/GetRecipeUpdateStateUseCase.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt

레시피 추가, 삭제, 수정을 담당하는 Repository에 상태를 Recipe 업데이트 상태를 관찰하는 flow를 만들고 이를 MyRecipeViewModel에서 collect 시켜 추가, 삭제, 수정 작업이 발생하면 Update된 레시피 목록을 새로 로드하게 함
presentation 레이어로 RecipeRepository로 부터 해당 flow를 불러오는 Usecase를 추가함
없음

[develop] 내 레시피 화면 레시피 추가, 삭제, 수정시 레시피 목록 초기화

---

data/src/main/java/com/kdjj/data/datasource/RecipeRemoteDataSource.kt
data/src/main/java/com/kdjj/data/repository/RecipeRepositoryImpl.kt
domain/src/main/java/com/kdjj/domain/di/UseCaseModule.kt
domain/src/main/java/com/kdjj/domain/model/request/FetchRemoteRecipeRequest.kt
domain/src/main/java/com/kdjj/domain/repository/RecipeRepository.kt
domain/src/main/java/com/kdjj/domain/usecase/FetchRemoteRecipeUseCase.kt
domain/src/main/java/com/kdjj/domain/usecase/SaveLocalRecipeUseCase.kt
remote/src/main/java/com/kdjj/remote/dao/RecipeServiceImpl.kt
remote/src/main/java/com/kdjj/remote/dao/RemoteRecipeService.kt
remote/src/main/java/com/kdjj/remote/datasource/RecipeRemoteDataSourceImpl.kt

레시피 개요 화면에서 필요한 Firebase에서 Recipe 정보 불러오기 기능과 불러온 Recipe정보를 로컬에 저장하는 훔쳐오기 기능을 구현
SaveLocalUseCase에서 External Storage에 대한 image path만 처리하였는데 Remote에 대한 image path도 처리할수 있도록 수정
없음

[develop ]  Remote에서 레시피 정보 불러오기, 로컬에 저장 

---

domain/src/main/java/com/kdjj/domain/usecase/UploadRecipeUseCase.kt

로컬에 저장된 레시피 업로드 할때 이미지를 FireStorage에서 저장한 후 imagePath를 받아 Recipe객체에 저장 후 업로드 하도록 수정 
없음
없음

[develop] UploadRecipeUseCase 수정

---

app/build.gradle
presentation/src/main/java/com/kdjj/presentation/common/IdGenerator.kt
presentation/src/main/java/com/kdjj/presentation/model/RecipeListItemModel.kt
presentation/src/main/java/com/kdjj/presentation/view/dialog/ConfirmDialogBuilder.kt
presentation/src/main/java/com/kdjj/presentation/view/dialog/CustomProgressDialog.kt
presentation/src/main/java/com/kdjj/presentation/view/recipesummary/RecipeSummaryActivity.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt

close #130
- 동일한 레시피를 여러 번 훔쳐오면 그 중 한 개만 정상 동작하는 오류 수정
- 로딩, 확인 화면 다른 곳 누르면 취소되는 문제 수정
- 레시피와 첫 번째 단계에 이미지 설정하면 저장이 이상하게 되는 오류 수정
- 레시피와 단계의 ID가 동일하여 이미지 저장에 오류 발생
- 확인, 로딩창 취소할 수 없도록 수정
- reduce에서 혹시나 발생할 수 있는 문제, fold로 수정
- 훔쳐오기 할 때 단계 아이디 변경

[develop] 4주차 배포 버전 오류 hotfix

---

remote/src/main/java/com/kdjj/remote/dao/RecipeListServiceImpl.kt
remote/src/main/java/com/kdjj/remote/datasource/RecipeListRemoteDataSourceImpl.kt

Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/147
fireStore paging 처리시 spendCancellableCoroutine 제거하고 , 
withContext 사용하도록 수정 
```kotlin
query.get(Source.SERVER).await()
```
query.get 에서 SERVER 에서만 가져오도록 강제할 수 있어서 더 이상 spendCancellableCoroutine 사용이 불필요해졌습니다. 
spendCancellableCoroutine 제거하고 withContext 로 수정했습니다. 
관련 Discussions : https://github.com/boostcampwm-2021/Android08-Ratatouille/discussions/91

[develop] fireStore paging 처리시, withContext 로 수정 

---

data/src/main/java/com/kdjj/data/common/ResultExtension.kt
data/src/main/java/com/kdjj/data/repository/RecipeImageRepositoryImpl.kt

Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/140
Result 확장함수 flatMap 적용

[develop] flatMap 적용 

---

presentation/build.gradle
presentation/src/main/java/com/kdjj/presentation/view/adapter/MyRecipeListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/OthersRecipeListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/RecipeDetailStepListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/RecipeDetailTimerListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/RecipeEditorListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/SearchRecipeListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/SingleViewTypeListAdapter.kt

Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/143
RecyclerView 에서 ViewHolder 가 recycle 될때, 
이미지뷰 Glide clear 처리 
09fd647538c85a98309969c9e85ea14ce9d1fc13

[develop] viewholder recycle 될때 Glide clear 처리 

---

presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt
remote/src/main/java/com/kdjj/remote/common/Utils.kt
remote/src/main/java/com/kdjj/remote/dao/RecipeServiceImpl.kt
remote/src/main/java/com/kdjj/remote/datasource/RecipeListRemoteDataSourceImpl.kt
remote/src/main/java/com/kdjj/remote/datasource/RecipeRemoteDataSourceImpl.kt

firestore에서 recipe 불러올때 suspendCancellableCoroutine 처리하지 않고 runcatching으로 에러 처리
fireStoreExceptionToDomain 함수 Common Package의 Utils 파일로 이동
없음

[develop] firestore recipe fetch 처리시 suspendCancellableCoroutine 제거

---

presentation/src/main/java/com/kdjj/presentation/model/RecipeEditorItem.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/OthersRecipeListAdapter.kt
presentation/src/main/java/com/kdjj/presentation/view/adapter/RecipeEditorListAdapter.kt

Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/142
RecipeEditorItem.kt 에 LiveData 프로퍼티 때문에 equals, hashCode 추가 
727d0ea7171b35702cc3cc7301898324df9c4691

[develop] RecipeEditorItem.kt equals, hashCode 추가 

---

presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt

Issue #135
- 내 레시피가 비어있는 상태에서 훔쳐오기 했을 때 crash 나는 문제 해결

fix: 개요 들어올 시 타입 업데이트 하는 기능 추가 close #135

---

presentation/src/main/java/com/kdjj/presentation/view/home/my/MyRecipeFragment.kt
presentation/src/main/java/com/kdjj/presentation/view/home/others/OthersRecipeFragment.kt
presentation/src/main/java/com/kdjj/presentation/view/home/search/SearchRecipeFragment.kt
presentation/src/main/java/com/kdjj/presentation/view/recipedetail/RecipeDetailActivity.kt
presentation/src/main/java/com/kdjj/presentation/view/recipeeditor/RecipeEditorActivity.kt
presentation/src/main/java/com/kdjj/presentation/view/recipesummary/RecipeSummaryActivity.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/others/OthersViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipedetail/RecipeDetailViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeEditorViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/search/SearchViewModel.kt

각 ViewModel 내부에 Event를 위한 LiveData가 많아져 Event를 위한 LiveData를 하나만 생성하고, 각 뷰모델에서 Event sealed class를 생성해 처리
Activity혹은 Fragment에서 각각의 LiveData를 Observe 하다가 Evnet를 관찰하는 관찰잘 하나에서 분기처리해 처리

[develop] Event sealed class 생성하여 Event LiveData 단일화

---

domain/src/main/java/com/kdjj/domain/common/IdGenerator.kt
domain/src/main/java/com/kdjj/domain/usecase/SaveLocalRecipeUseCase.kt
local/src/main/java/com/kdjj/local/FileSaveHelper.kt
local/src/main/java/com/kdjj/local/dao/ImageValidationDao.kt
local/src/main/java/com/kdjj/local/dao/RecipeDao.kt
local/src/main/java/com/kdjj/local/dataSource/RecipeImageLocalDataSourceImpl.kt
local/src/main/java/com/kdjj/local/dataSource/RecipeListLocalDataSourceImpl.kt
local/src/main/java/com/kdjj/local/dataSource/RecipeLocalDataSourceImpl.kt
local/src/main/java/com/kdjj/local/database/RecipeDatabase.kt
local/src/main/java/com/kdjj/local/di/LocalRecipeImageModule.kt
local/src/main/java/com/kdjj/local/di/LocalRecipeListModule.kt
local/src/main/java/com/kdjj/local/di/LocalRecipeModule.kt
local/src/main/java/com/kdjj/local/di/LocalRecipeTypeModule.kt
local/src/main/java/com/kdjj/local/dto/ImageValidation.kt
local/src/main/java/com/kdjj/local/dto/ImageValidationDto.kt

Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/178
레시피 저장 로직 수정했습니다. 
레시피 저장과 훔쳐오기까지 정상 동작하는 것 확인했습니다. 
Discussion 참고해주세요 : https://github.com/boostcampwm-2021/Android08-Ratatouille/discussions/172
UUID로 id 생성하는 IdGenerator 추가해두었습니다. : 05803571008fdb09e8fd03156d5255659aeeb2cf

[develop] recipe 저장 

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/kdjj/ratatouille/app/App.kt
build.gradle
domain/src/main/java/com/kdjj/domain/model/request/UpdateRemoteRecipeRequest.kt
domain/src/main/java/com/kdjj/domain/usecase/UpdateLocalRecipeUseCase.kt
domain/src/main/java/com/kdjj/domain/usecase/UpdateRemoteRecipeUseCase.kt
presentation/build.gradle
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/kdjj/presentation/common/Utils.kt
presentation/src/main/java/com/kdjj/presentation/di/PresentationModule.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeEditorViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeUploadWorker.kt
remote/src/main/java/com/kdjj/remote/di/RemoteModule.kt

Issue #183
- WorkManager를 이용하여 유저가 업로드한 레시피가 수정될 경우 FireStore에 올리는 기능 구현
- 만약, 네트워크 연결이 되어있지 않은 경우 연결된 후 작업하도록 설정

[develop, domain] WorkManager를 이용한 작업 예약 #183

---

presentation/src/main/java/com/kdjj/presentation/view/home/my/MyRecipeFragment.kt
presentation/src/main/java/com/kdjj/presentation/view/home/others/OthersRecipeFragment.kt
presentation/src/main/java/com/kdjj/presentation/view/home/search/SearchRecipeFragment.kt
presentation/src/main/java/com/kdjj/presentation/view/recipesummary/RecipeSummaryActivity.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/others/OthersViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeEditorViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/search/SearchViewModel.kt
presentation/src/main/res/layout/activity_recipe_editor.xml
presentation/src/main/res/layout/activity_recipe_summary.xml
presentation/src/main/res/layout/item_editor_add_step.xml
remote/src/main/java/com/kdjj/remote/common/Utils.kt

Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/186
중복 클릭 방지를 위한 Throttle 처리 
fragment 에서 navigate 로 화면 이동 후 다시 돌아오면 onViewCreate() 부터 다시 호출되어, 
PublishSubject 를 여러번 구독하게 되는 현상이 발생합니다. 
그래서 Throttle 처리할 버튼 클릭 이벤트와 나머지 이벤트를 분리하여, 
Throttle 처리할 버튼 클릭 이벤트는 onCreate() 에서 설정하도록 했습니다. 88b71083daee1bc7ee6c568a5129cc5c08214081

[develop] 클릭 throttle 처리 

---

presentation/src/main/java/com/kdjj/presentation/view/recipesummary/RecipeSummaryActivity.kt
presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt
presentation/src/main/res/layout/activity_recipe_summary.xml

Issue #209
- 레시피 삭제 시 유저에게 한번 묻는 기능 구현

[develop] 레시피 삭제 전에 유저에게 한번 더 묻는 창 보여주는 기능 구현 #209

---

presentation/src/main/res/layout/activity_recipe_summary.xml

Issue #214
- 레시피 로드 전 레시피 개요 항목 보이지 않도록 수정

[develop] 레시피 로딩전에 항목 보이지 않도록 수정 #214

---

app/build.gradle
data/src/main/java/com/kdjj/data/datasource/RecipeImageLocalDataSource.kt
data/src/main/java/com/kdjj/data/datasource/RecipeImageRemoteDataSource.kt
data/src/main/java/com/kdjj/data/repository/RecipeImageRepositoryImpl.kt
data/src/test/java/com/kdjj/data/recipeimage/RecipeImageRepositoryImplTest.kt
domain/src/main/java/com/kdjj/domain/model/ImageInfo.kt
domain/src/main/java/com/kdjj/domain/repository/RecipeImageRepository.kt
domain/src/main/java/com/kdjj/domain/usecase/SaveLocalRecipeUseCase.kt
domain/src/main/java/com/kdjj/domain/usecase/UpdateLocalRecipeUseCase.kt
local/src/main/java/com/kdjj/local/ImageFileHelper.kt
local/src/main/java/com/kdjj/local/dataSource/RecipeImageLocalDataSourceImpl.kt
local/src/test/java/com/kdjj/local/dataSource/RecipeImageLocalDataSourceImplTest.kt
remote/src/main/java/com/kdjj/remote/datasource/RecipeImageRemoteDataSourceImpl.kt
remote/src/main/java/com/kdjj/remote/service/FirebaseStorageService.kt
remote/src/main/java/com/kdjj/remote/service/FirebaseStorageServiceImpl.kt
remote/src/test/java/com/kdjj/remote/recipe/RecipeImageRemoteDataSourceImplTest.kt

Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/219
파이어베이스 스토리지에서 이미지 가져올때, 
로컬에 이미지 저장할때 withContext 안에서 async 처리 
- 이미지 비동기 처리 수정  b02aefecb0115330e0ed460b3dbe21bbe10c5265

[develop] save recipe 이미지 처리 비동기 
