boostcampwm-2021/Android08-Ratatouille

domain/src/main/java/com/kdjj/domain/model/Recipe.kt, domain/src/main/java/com/kdjj/domain/model/RecipeState.kt, local/src/main/java/com/kdjj/local/Mapper.kt, presentation/src/main/java/com/kdjj/presentation/common/IdGenerator.kt, presentation/src/main/java/com/kdjj/presentation/common/RecipeMapper.kt, presentation/src/main/java/com/kdjj/presentation/common/Utils.kt, presentation/src/main/java/com/kdjj/presentation/model/RecipeItem.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeEditorViewModel.kt
- Recipe상태를 별도의 변수로 분리
- authorId 필수 입력으로 수정
=> [develop] 도메인 Recipe 모델 수정

app/build.gradle, app/src/main/java/com/kdjj/ratatouille/di/data/RecipeImageModule.kt, data/src/main/java/com/kdjj/data/recipeimage/RecipeImageLocalDataSource.kt, data/src/main/java/com/kdjj/data/recipeimage/RecipeImageRemoteDataSource.kt, data/src/main/java/com/kdjj/data/recipeimage/RecipeImageRepositoryImpl.kt, data/src/main/java/com/kdjj/data/recipetype/RecipeImageLocalDataSource.kt, domain/src/main/java/com/kdjj/domain/repository/RecipeImageRepository.kt, local/build.gradle, local/src/main/java/com/kdjj/local/FileSaveHelper.kt, local/src/main/java/com/kdjj/local/dataSource/RecipeImageLocalDataSourceImpl.kt, remote/build.gradle, remote/src/main/java/com/kdjj/remote/FirebaseStorageDao.kt, remote/src/main/java/com/kdjj/remote/FirebaseStorageDaoImpl.kt, remote/src/main/java/com/kdjj/remote/recipe/RecipeImageRemoteDataSourceImpl.kt
=> [develop] RecipeImage Repository 구현

data/build.gradle, data/src/test/java/com/kdjj/data/recipeimage/RecipeImageRepositoryImplTest.kt, local/src/test/java/com/kdjj/local/dataSource/RecipeImageLocalDataSourceImplTest.kt, remote/src/test/java/com/kdjj/remote/recipe/RecipeImageRemoteDataSourceImplTest.kt
=> [develop] data, local, remote RecipeImageRepository, RecipeLocalDataSource, RecipeRemoteDataSource 테스트 #52

data/src/main/java/com/kdjj/data/datasource/RecipeLocalDataSource.kt, data/src/main/java/com/kdjj/data/repository/RecipeRepositoryImpl.kt, domain/src/main/java/com/kdjj/domain/model/request/GetLocalRecipeRequest.kt, domain/src/main/java/com/kdjj/domain/repository/RecipeRepository.kt, domain/src/main/java/com/kdjj/domain/usecase/GetLocalRecipeUseCase.kt, local/src/main/java/com/kdjj/local/dao/RecipeDao.kt, local/src/main/java/com/kdjj/local/dataSource/RecipeLocalDataSourceImpl.kt
Issue #92 
- Database에서 RecipeFlow 가져오는 기능 구현
=> [develop] RecipeLocalDataSource, RecipeRepository RecipeFlow가져오는 기능 구현 #92

presentation/src/main/java/com/kdjj/presentation/view/adapter/MyRecipeListAdapter.kt, presentation/src/main/java/com/kdjj/presentation/view/home/HomeActivity.kt, presentation/src/main/java/com/kdjj/presentation/view/home/my/MyRecipeFragment.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt
HomeActivity와 MyRecipeListAdapter 버그 발생 코드 수정
없음
없음
=> [develop] HomeActivity와 MyRecipeListAdapter 버그 수정

presentation/src/main/java/com/kdjj/presentation/view/adapter/RecipeDetailStepListAdapter.kt, presentation/src/main/java/com/kdjj/presentation/view/adapter/RecipeDetailTimerListAdapter.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/recipedetail/RecipeDetailViewModel.kt
이전 PR에 반영하지 못한 수정사항
- 불필요한 함수 제거
- 힐트 어노테이션 추가
=> [develop] 상세 화면 수정사항

presentation/src/main/java/com/kdjj/presentation/model/MyRecipeItem.kt, presentation/src/main/java/com/kdjj/presentation/view/adapter/MyRecipeListAdapter.kt, presentation/src/main/java/com/kdjj/presentation/view/home/my/MyRecipeFragment.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt, presentation/src/main/res/layout/fragment_my_recipe.xml, presentation/src/main/res/layout/item_my_recipe.xml, presentation/src/main/res/layout/item_my_recipe_progress.xml, presentation/src/main/res/values/strings.xml
Room DB에서 데이터 로드 실패 대응, 사용자 피드백
없음
없음
=> [develop] 내 레시피 화면 추가기능 구현

presentation/src/main/java/com/kdjj/presentation/di/PresentationModule.kt, presentation/src/main/java/com/kdjj/presentation/model/StepTimerModel.kt, presentation/src/main/java/com/kdjj/presentation/view/adapter/RecipeDetailTimerListAdapter.kt, presentation/src/main/java/com/kdjj/presentation/view/splash/LaunchActivity.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/recipedetail/RecipeDetailViewModel.kt, presentation/src/main/res/layout/activity_recipe_detail.xml, presentation/src/main/res/layout/item_detail_timer.xml
Issue: https://github.com/boostcampwm-2021/Android08-Ratatouille/issues/109
타이머 끝날때 애니메이션 추가
=> [develop] 타이머 애니메이션 

domain/src/main/java/com/kdjj/domain/usecase/UpdateRemoteRecipeUseCase.kt, presentation/src/main/java/com/kdjj/presentation/model/RecipeEditorItem.kt, presentation/src/main/java/com/kdjj/presentation/view/home/my/MyRecipeFragment.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeEditorViewModel.kt
close #132
긴급 패치 2탄
- 수정 및 업로드 이슈 해결
- 내 레시피 화면 프로그래스바 수정
- 레시피 수정 시 업로드 상태면 서버에 반영
- 흔들리는 레시피 속의 프로그래스바 구출
=> [develop] 4주차 배포 버전 2차 hotfix

app/src/main/res/values-night/themes.xml, presentation/src/main/java/com/kdjj/presentation/view/splash/LaunchActivity.kt
close #134
- 다크 모드의 테마를 NoActionBar로 변경
- 홈 화면으로 이동 후 Splash 종료
=> [develop] 다크모드 crash 수정

presentation/src/main/java/com/kdjj/presentation/view/adapter/MyRecipeListAdapter.kt, presentation/src/main/java/com/kdjj/presentation/view/home/my/MyRecipeFragment.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt
MyRecipeViewModel에 같은 동작을 하는 함수가 여러개 존제하여 한 함수에서 처리할수 있도록 수정
없음
없음
=> [develop] MyRecipeViewModel 수정

presentation/src/main/java/com/kdjj/presentation/model/ConfirmDialogModel.kt, presentation/src/main/java/com/kdjj/presentation/view/adapter/RecipeDetailStepListAdapter.kt, presentation/src/main/java/com/kdjj/presentation/view/dialog/ConfirmDialogBuilder.kt, presentation/src/main/java/com/kdjj/presentation/view/home/search/SearchRecipeFragment.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/search/SearchViewModel.kt, presentation/src/main/res/layout/dialog_confirm.xml, presentation/src/main/res/layout/fragment_search_recipe.xml, presentation/src/main/res/values/dimens.xml, presentation/src/main/res/values/strings.xml
close #137
검색 화면의 스낵바 작업
- 네트워크, 파이어베이스 에러는 스낵바로 표시
- detail의 step list adapter에 executePendingBindings 추가
- 검색 중일 때 UI에 표시
- 취소가 있는 알림창 추가
- 검색 화면에 스낵바 추가
- 검색 중일 때 progress circle 추가
- CustomConfirmDialog에 cancel 추가
=> [develop] 검색 화면 스낵바

presentation/src/main/java/com/kdjj/presentation/view/home/my/MyRecipeFragment.kt, presentation/src/main/java/com/kdjj/presentation/view/home/my/SpacesItemDecoration.kt, presentation/src/main/res/layout/fragment_my_recipe.xml, presentation/src/main/res/layout/item_my_recipe.xml, presentation/src/main/res/layout/item_my_recipe_add_recipe.xml, presentation/src/main/res/layout/item_my_recipe_progress.xml, presentation/src/main/res/values/dimens.xml
width의 길이가 변경되어도 item 사이의 간격은 유지하고 화면에 표시될 아이템의 수만 동적으로 처리
=> [develop] spancount에 따른 View 크기 동적 지정 및 View간의 간격 유지

data/src/main/java/com/kdjj/data/repository/RecipeRepositoryImpl.kt, presentation/src/main/java/com/kdjj/presentation/model/RecipeEditorItem.kt, presentation/src/main/java/com/kdjj/presentation/model/StepTimerModel.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeEditorViewModel.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt, presentation/src/main/res/layout/item_detail_timer.xml
close #146
- 타이머 종료 후 재실행했을 때 종료 후 색상 유지되는 이슈 해결
- 리뷰 반영
- TimerModel에 State 추가
- notifyChanges로 관리되던 리스트 LiveData로 변경
- 불필요한 switchMap을 map으로 변경
- 불필요한 also 제거
=> [develop] 타이머 색상, 리뷰 반영

domain/src/main/java/com/kdjj/domain/model/request/FetchRemoteRecipeRequest.kt, domain/src/main/java/com/kdjj/domain/repository/RecipeRepository.kt, domain/src/main/java/com/kdjj/domain/usecase/FetchRemoteRecipeUseCase.kt, remote/src/main/java/com/kdjj/remote/datasource/RecipeImageRemoteDataSourceImpl.kt, remote/src/main/java/com/kdjj/remote/datasource/RecipeListRemoteDataSourceImpl.kt, remote/src/main/java/com/kdjj/remote/datasource/RecipeRemoteDataSourceImpl.kt, remote/src/main/java/com/kdjj/remote/datasource/RecipeTypeRemoteDataSourceImpl.kt, remote/src/main/java/com/kdjj/remote/di/RemoteRecipeImageModule.kt, remote/src/main/java/com/kdjj/remote/di/RemoteRecipeListModule.kt, remote/src/main/java/com/kdjj/remote/di/RemoteRecipeModule.kt, remote/src/main/java/com/kdjj/remote/di/RemoteRecipeTypeModule.kt, remote/src/main/java/com/kdjj/remote/service/FirebaseStorageService.kt, remote/src/main/java/com/kdjj/remote/service/FirebaseStorageServiceImpl.kt, remote/src/main/java/com/kdjj/remote/service/FirestoreService.kt, remote/src/main/java/com/kdjj/remote/service/FirestoreServiceImpl.kt, remote/src/main/java/com/kdjj/remote/service/RecipeListServiceImpl.kt, remote/src/main/java/com/kdjj/remote/service/RecipeServiceImpl.kt, remote/src/main/java/com/kdjj/remote/service/RemoteRecipeListService.kt, remote/src/main/java/com/kdjj/remote/service/RemoteRecipeService.kt, remote/src/test/java/com/kdjj/remote/recipe/RecipeImageRemoteDataSourceImplTest.kt, remote/src/test/java/com/kdjj/remote/recipe/RecipeTypeRemoteDataSourceImplTest.kt
Issue #156
- fetchRemoteRecipe 카멜케이스 지키도록 네이밍 변경
- dao 로 네이밍 되어있는거 변경
- service가 dto를 반환하도록 코드 수정
=> Feature/code refactoring #156

app/build.gradle
=> [develop] 버전 업데이트

domain/src/main/java/com/kdjj/domain/usecase/SaveLocalRecipeUseCase.kt, domain/src/main/java/com/kdjj/domain/usecase/UpdateLocalRecipeFavoriteUseCase.kt, presentation/src/main/java/com/kdjj/presentation/model/UpdateFavoriteResult.kt, presentation/src/main/java/com/kdjj/presentation/services/TimerService.kt, presentation/src/main/java/com/kdjj/presentation/view/recipesummary/RecipeSummaryActivity.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/recipedetail/RecipeDetailViewModel.kt, presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt, presentation/src/main/res/drawable/bg_summary_fab.xml, presentation/src/main/res/drawable/ic_baseline_keyboard_arrow_down_24.xml, presentation/src/main/res/drawable/ic_baseline_star_16dp.xml, presentation/src/main/res/layout/activity_recipe_summary.xml, presentation/src/main/res/values/dimens.xml
Issue #195
- 화면 회전시 플로팅 메뉴 사라지는 현상 수정
- 플로팅 버튼 상태에 따른 아이콘 수정
- 즐겨찾기 추가 / 제거 문구 변경
- 즐겨찾기 상태에 따른 아이콘 변경
#197
=> [develop] RecipeSummary 화면 플로팅 버튼 관련 버그 및 코드수정 #195

presentation/src/main/res/layout/activity_splash.xml, presentation/src/main/res/values/dimens.xml
디바이스 크기에따라 이미지가 짤릴것을 대비해 고정값을 부여함
=> [develop] Splash화면 이미지 크기 수정

presentation/src/main/java/com/kdjj/presentation/view/bindingadapter/TextViewBindingAdapter.kt, presentation/src/main/res/layout/activity_recipe_summary.xml, presentation/src/main/res/values/colors.xml, presentation/src/main/res/values/dimens.xml, presentation/src/main/res/values/strings.xml, presentation/src/main/res/values/styles.xml
Issue #201
- 레시피 개요 디자인 변경
- 레시피 개요 디자인 변경
=> [develop] 레시피 개요 디자인 변경 #201

presentation/src/main/res/layout/activity_recipe_summary.xml, presentation/src/main/res/values/dimens.xml
=> [develop] 레시피 개요 이미지 코너 둥글게 구현 #212

presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt
=> [develop] 내 레시피 화면 progress바 수정

presentation/src/main/java/com/kdjj/presentation/view/bindingadapter/RecyclerViewBindingAdapter.kt, presentation/src/main/java/com/kdjj/presentation/view/recipedetail/RecipeDetailActivity.kt
close #222
- RecyclerView submitList할 때 decoration 업데이트
- 알림창에 일시정지된 타이머도 돌아가는 문제 수정
=> [develop] 5주차 배포 hotfix
